-- 2017_0929 김재림 v 1.0
-- 체형정보
insert into bodys values('100','허벅지만 굵은','허벅지만 굵은');
insert into bodys values('200','하체비만','하체비만');
insert into bodys values('300','상체비만','상체비만');
insert into bodys values('400','상체빈약','상체빈약');
insert into bodys values('500','하체빈약','하체빈약');
insert into bodys values('600','전체적으로 빈약','전체적으로 빈약');
insert into bodys values('700','전체적으로 비만','전체적으로 비만');
insert into bodys values('800','뱃살이 많은','뱃살이 많은');