-- 2017_0929 김재림 V 1.0
--zipcode_old DML에 해당하는 부분

--우편주소 DB 삽입(insert)
--insert into members values(?,?,?,?,?,?,?,?);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('135-811','서울','강남구','논현1동',null,null,'12∼17',71);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('612-868','부산','해운대구','우1동',null,'해운대반도보라빌아파트','(101∼107동)',11373);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('705-830','대구','남구','봉덕1동',null,null,'980∼982',11866);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('400-821','인천','중구','운북동',null,null,'934∼1250',15794);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('500-520','광주','북구','운정동',null,null,null,16999);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('219-812','강원','고성군','현내면','초도리',null,null,20674);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('423-813','경기','광명시','광명7동',null,null,'295∼296',22692);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('680-830','울산','남구','신정4동',null,null,'874∼879',18495);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('306-150','대전','대덕구','삼정동',null,null,null,17446);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('636-981','경남','의령군','지정면','오천리',null,null,33468);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('745-833','경북','문경시','산북면','내화리',null,null,35673);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('542-800','전남','구례군','구례읍',null,'구례우체국',null,40813);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('573-880','전북','군산시','소룡동',null,null,'301∼999',43153);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('331-813','충남','천안시 서북구','직산읍','마정리',null,null,48219);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('380-932','충북','충주시','살미면','문강리',null,null,50428);
Insert into ZIPCODE_OLD (ZIPCODE,SIDO,GUGUN,DONG,RI,BLDG,BUNJI,SEQ) values ('695-969','제주','제주시','조천읍','신흥리',null,null,46174);
